# Configurazione del Sito
title: Radio Moguri
email: radiomoguri@gmail.com
author: Andrea Corinti
description: Video Game Music Radio
url:  https://radiomoguri.github.io
baseurl: ""
lang: it_IT

# Collection / Autori

collections:
  authors:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Logo
logo: "/assets/immagini/logomoguri.png" # idealmente, 150x150px

# Build settings
permalink: :title/
sass:
  sass_dir: _sass

# Social

social:
  name: Radio Moguri
  links:
    - https://twitter.com/radiomoguri
    - https://www.facebook.com/radiomoguri

show_social_icons: true

facebook:
  publisher: radiomoguri
  admins: galbadia

twitter:
  username: radiomoguri

instagram: radiomoguri

# Plugin
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Paginate
paginate: 3 # imposta il numero di news visibili nella home
