remote_theme: "mmistakes/so-simple-theme"

locale: it-It
title: "Radio Moguri"
description: "Italian Gaming Web Radio! Semi di kupò sempre graditi ❤"
logo: "Mog_21.jpg" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Footer Links
footer_links:
  - title: Facebook
    url: https://facebook.com/radiomoguri
    icon: fab fa-facebook
  - title: Youtube
    url: https://www.youtube.com/channel/UCUGqWnf2rMqxVc_toRoXjRg
    icon: fab fa-youtube    
  - title: Instagram
    url: https://instagram.com/radiomoguri
    icon: fab fa-instagram
  - title: Steam
    url: https://steamcommunity.com/groups/radiomoguri
    icon: fab fa-steam
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

