# Configurazione del Sito
title: Radio Moguri
email: radiomoguri@gmail.com
author: Andrea Corinti
description: Game Kupò Radio
url:  #
baseurl: ""

# Collection / Autori

collections:
  authors:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Logo
logo: "/assets/immagini/logomoguri.png" # idealmente, 150x150px

# Build settings
permalink: :title/
sass:
  sass_dir: _sass

# Social
show_social_icons: true
facebook: radiomoguri
instagram: radiomoguri
twitter: radiomogurihub

# Plugin
plugins:
  - jekyll-paginate

# Paginate
paginate: 3 # imposta il numero di news visibili nella home
